Cloud bastion
Otus-DevOps-2022-02/ashfauihf_infra pull request #7
Opened 2022-03-25 08:52 UTC by ashfauihf

2022-03-25 17:35 UTC, mrgreyves requested changes
Здравствуйте!)
Нужно добавить описание к вашему пуллреквесту
<img width="921" alt="image" src="https://user-images.githubusercontent.com/34331259/160172655-944882cb-1408-4877-92f9-b22ea7538922.png">

2022-03-25 18:16 UTC, ashfauihf commented
#ashfauihf_infra 
5 Лекция 
   Первое задание. 
Подключение к внутреннему хосту (someinternalhost) в одну строку Используя команду ssh -i ~/.ssh/appuser -J appuser@51.250.13.201 appuser@10.128.0.17 
   Второе задание Создаем файл по пути ~/.ssh/config Файле вбиваем название хостов, ip адреса, пользователя под кем будет подключение. 
   #bastion host
Host bastion 
hostname 51.250.13.201 
User appuser 
#someinternalhost host
host someinternalhost 
hostname 10.128.0.17 
User appuser 
ProxyJump bastion 
  Третье задание 
bastion_IP = 51.250.13.201
 someinternalhost_IP = 10.128.0.17

2022-03-25 18:16 UTC, ashfauihf commented
Добавил

пт, 25 мар. 2022 г. в 20:35, Vladimir Drozdetskiy ***@***.***
>:

> ***@***.**** requested changes on this pull request.
>
> Здравствуйте!)
> Нужно добавить описание к вашему пуллреквесту
> [image: image]
> <https://user-images.githubusercontent.com/34331259/160172655-944882cb-1408-4877-92f9-b22ea7538922.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Otus-DevOps-2022-02/ashfauihf_infra/pull/7#pullrequestreview-921956088>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVSCN7P4QWBTGZ65J5B4GSDVBX2PNANCNFSM5RTQXE4A>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-03-26 05:36 UTC, closed without merging

2022-03-26 05:36 UTC, ashfauihf commented
#ashfauihf_infra
5 Лекция
Первое задание.
Подключение к внутреннему хосту (someinternalhost) в одну строку Используя команду ssh -i ~/.ssh/appuser -J appuser@51.250.13.201 appuser@10.128.0.17
Второе задание Создаем файл по пути ~/.ssh/config Файле вбиваем название хостов, ip адреса, пользователя под кем будет подключение.
#bastion host
Host bastion
hostname 51.250.13.201
User appuser
#someinternalhost host
host someinternalhost
hostname 10.128.0.17
User appuser
ProxyJump bastion
Третье задание
bastion_IP = 51.250.13.201
someinternalhost_IP = 10.128.0.17